# Event name
  name: on_push
# When the event should run
  on:
    push:
      branches:
      #- "**" # This will run on all branches and must be quoted to be handled by yaml
      - main
# What jobs to execute
  jobs:
    build_and_test:
      runs-on: ubuntu-latest
      env:
        HEADLESS_CHROME: true
      steps:
        - name: Make sure pipeline has access to the codebase
          uses: actions/checkout@v2
        - name: Install Java
          uses: actions/setup-java@v3
          with:
            distribution: 'liberica'
            java-version: '18'
            java-package: jdk
        - name: Run tests with Maven
          working-directory: webdriver_java
          run: mvn test